### ISSUE TITLE
group is not a function

### ISSUE THREAD

**Issue by fdorantesm** [dirkgroenen/express-group-routes#1]
Hi Dirk, thanks for this mod.

I tried to use it, but i couldn't do it because group function doesn't exists:

app.group("/api/v1", (router) =>{
    ^
```
TypeError: app.group is not a function
    at Object.<anonymous> (/www/nodejs/apiblog/config/routes.js:10:5)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/www/nodejs/apiblog/app.js:8:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```
What i'm doing wrong?
```
var app = require('express')
// var router = express.Router()
require('express-group-routes');

var userController = require('../controllers/userController')
var mainController = require('../controllers/mainController')
var postController = require('../controllers/postController')

// router.get('/api',mainController.index)
app.group("/api/v1", (router) =>{
	router.get("/user/:id",userController.user)
	router.get("/users",userController.users)
	router.get("/posts",postController.posts)
	router.get("/posts/:id",postController.post)
})

module.exports = router
```

**Comment by Smahrt** [comment]
I have this same issue. Have you found a solution yet?

**Comment by fdorantesm** [comment]
Nope, but i used route function.

```
router.route('/api/v1')
    .post((req, res)=>{ })
    .get((req, res)=>{ })
```

;)

**Comment by domzgarcia** [comment]
Hi @fdorantesm, you should include `express-group-routes` before you invoke this `express()`
because its kind of prototyping inside the core.

https://github.com/domzgarcia/social-monitoring-v4/blob/master/core/bootstrap/RoutesManager.js#L10

**Comment by reisap** [comment]
for handle this issue please provide like this.

require('express-group-routes'); //<-------need first implementation
import express from "express";// Init an Express App. 

//.....line of code

app.group("/api/v1", (router) =>{
	router.get("/user/:id",userController.user)
	router.get("/users",userController.users)
	router.get("/posts",postController.posts)
	router.get("/posts/:id",postController.post)
});

//hope this help. :)
